services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/Containers/postgres/data:/var/lib/postgresql/data
      - ${HOME}/Containers/postgres/path/pg_config:/usr/bin/pg_config
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      - ${HOME}/Containers/postgres/pgadmin/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.cl"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - 7020:80
    depends_on:
      - postgres
