#!/bin/sh

# System Stuff

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Sensible Env Variables
$HOME/dotfiles/scripts/sensible_env.sh

# Env Variables
source "$HOME/dotfiles/scripts/env_variables.sh"

# Start Programs

# X Server config
setxkbmap -layout latam -option grp:shifts_toggle,caps:escape &
xsetroot -cursor_name left_ptr &
$HOME/.screenlayout/home.sh

udiskie &
picom -b --experimental-backends &
xss-lock -l -- i3lock-fancy-dualmonitor &
dunst &
polkit-dumb-agent &
thunar --daemon &
kdeconnect-indicator &
nexcloud --background &

# Start Window Manager or Desktop Enviroment
exec i3
