#!/bin/sh
# shellcheck disable=2086,1090,1091,3046,3020

# System Stuff

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Env Variables
source "$HOME/dotfiles/scripts/env_variables.sh"

# Start Programs

# X Server config
setxkbmap -layout latam &
xsetroot -cursor_name left_ptr &
$HOME/.screenlayout/screen.sh

udiskie &
picom -b --experimental-backends &
# xss-lock -l -- i3lock-fancy-dualmonitor &
xss-lock -l -- &
dunst &
polkit-dumb-agent &
thunar --daemon &
kdeconnect-indicator &
easyeffects --gapplication-service &>/dev/null &
playerctld &>/dev/null &
numlockx &

# Start Window Manager or Desktop Enviroment
exec i3
