#!/usr/bin/env bash

# Start flavours
# Scheme Name   : Porple
# Scheme Author : Niek den Breeje (https://github.com/AuditeMarlow)

base00="#292c36" # Default Background
base01="#333344" # Lighter Background (Used for status bars)
base02="#474160" # Selection Background
base03="#65568a" # Comments, Invisibles, Line Highlighting
base04="#b8b8b8" # Dark Foreground (Used for status bars)
base05="#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06="#e8e8e8" # Light Foreground (Not often used)
base07="#f8f8f8" # Light Background (Not often used)
base08="#f84547" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09="#d28e5d" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A="#efa16b" # Classes, Markup Bold, Search Text Background
base0B="#95c76f" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C="#64878f" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D="#8485ce" # Functions, Methods, Attribute IDs, Headings
base0E="#b74989" # Keywords, Storage, Selector, Markup Italic, Diff Changed
# End flavours

transparent="#00000000"
bspc config normal_border_color "$base00"
bspc config active_border_color "$base00"
bspc config focused_border_color "$base01"
bspc config presel_border_color "$base02"
