services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Chile/Santiago
    volumes:
      - ${HOME}/Containers/syncthing/config:/config
      - ${HOME}/Pictures:/data/Pictures
      - ${HOME}/Music:/data/Music
    ports:
      - 7200:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
