#!/usr/bin/env bash

rofi_theme="-theme $HOME/.config/rofi/themes/sidebar.rasi"

# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${entries[@]}" | sort | rofi $rofi_theme -dmenu -p 'Edit config')

# What to do when/if we choose a file to edit.
if [ "$choice" ]; then
	cfg=$(printf '%s\n' "${common_entries["${choice}"]}")
	if [[ -n "$cfg" ]]; then
		$terminal_directory "$cfg" $EDITOR
	else
		$terminal_directory "$choice" $EDITOR
	fi

# What to do if we just escape without choosing anything.
else
	echo "Program terminated." && exit 0
fi
