#!/usr/bin/env bash

# Create better theme for this
rofi_theme="-theme $HOME/.config/rofi/themes/sidebar.rasi"

cmd=$(rofi $rofi_theme -dmenu -p "Enter a command" -l 0)

if [ "$cmd" ]; then

    rofi $rofi_theme -e "$($cmd)"

fi
