#!/usr/bin/env bash

rofi_theme="-theme $HOME/.config/rofi/themes/sidebar.rasi"

declare -A links

links[usercode]="https://meet.google.com/cst-ywbc-ebk"
links[procomercial-dev]="https://meet.google.com/zxq-ohvh-pma"

# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${!links[@]}" | sort | rofi $rofi_theme -dmenu -p 'Edit config')

if [ "$choice" ]; then
  brave "${links[$choice]}"
else 
  brave "$choice"
fi
