require("plugins.autoformat")
require("plugins.autopairs")
require("plugins.cheetsheet")
require("plugins.dashboard")
require("plugins.easyalign")
require("plugins.harpoon")
require("plugins.indent-lines")
require("plugins.markdown-preview")
require("plugins.nvim-comment-frame")
require("plugins.nvim-mapper")
require("plugins.nvim-toggleterm")
require("plugins.nvim-tree")
require("plugins.nvim_lsp")
require("plugins.snippets")
require("plugins.treesitter")
require("plugins.twilight")
require("plugins.twilight")
require("plugins.which-key")

-- vim repeat (need to be after plugin config)
vim.cmd([[silent! call repeat#set("\<Plug>MyWonderfulMap", v:count)]])
