#!/bin/bash
# vim:foldmethod=marker

## Variables {{{

dependencies=(git ranger timeshift gio fd)

max_backups=5
backup_message="After Update Backup"
bookmarks_backup_path="$Home/Nextcloud/principal/Misc/bookmarks_backup.md"

# Colors
red="\e[0;91m"
blue="\e[0;94m"
expand_bg="\e[K"
blue_bg="\e[0;104m${expand_bg}"
red_bg="\e[0;101m${expand_bg}"
green_bg="\e[0;102m${expand_bg}"
green="\e[0;92m"
white="\e[0;97m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"

function usage ()
{
	echo "Usage :  $0 [options] [--]

	Options:
	-h|help         Display this message
	-G|no-git       Don't update git repos
	-B|no-backup    Don't create a backup
	-W|no-wallpaper Don't change the wallpaper"

}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

do_git=true
do_backup=true
do_wallpaper=true

while getopts ":hBG" opt
do
	case ${opt} in

		h|help     )  usage; exit 0   ;;

		G|no-git   ) do_git=false ;;

		B|no-backup ) do_backup=false ;;

		W|no-wallpaper ) do_wallpaper=false ;;

		* )  echo -e "\n  Option does not exist : OPTARG\n"
			usage; exit 1   ;;

		esac    # --- end of case ---
	done

## Variables }}}

## 0.- Initialization {{{

for dep in "${dependencies[@]}"; do
	if ! command -v "$dep" &> /dev/null; then
		echo -e "$red${dep}$reset not fount!"
		exit 1
	fi
done

## 0.- Initialization }}}

## 1.- Delete Unused Packages {{{

# Unused packages
# TODO

# Delete orphans packages
echo -e "checking orphan packages"
# pacman -Qtdq | pacman -Rns -
paru -cc

## 1.- Delete Unused Packages }}}

## 2.- Update System {{{

# Update system packages
echo -e "Updating System"
paru

# Update Python packages
pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U

# Update npm pacages
sudo npm update -g

# Update nvim packages
# PLUG=no disable some plugins
echo -e "Updating vim plugins"
PLUG=no nvim "+PackerSync" "+au BufLeave * qa!"

# update fish packages
fish -c "fundle update"


## 2.- Update System  }}}

## 3.- Clean system {{{

# Clean pacman and paru cache
paru -Sc --noconfirm && paccache -rk2

## 3.- Clean system }}}

## 4.- Clean Custom Folders {{{

# ~/Downloads

# (xdg-user-dir DOWNLOAD)
# (
#   "Music"
#   "Video"
#   "Pasar al Server"
#   "U"
# )

# ~/.config
# TODO

## 4.- Clean Custom Folders }}}

## 5.- Clean Trash {{{

## Autotrash do this automatically c:

## 5.- Clean Trash }}}

## 6.- Backup Stuff {{{

# Dotfiles
if $do_git; then
	cd "$dotfile_folder"
	git_untracked=($(echo "$(git status --porcelain)" | awk '$1 == "??" {print $2}'))

	git commit -a -m "update $(date +'%m-%d-%Y')"
	git push origin master

	cd "$HOME"
fi

# bookmarks
buku --export "$bookmarks_backup_path"

## 6.- Backup Stuff }}}

## 7.- Sort Wallpapers {{{

sort_wallpapers.py

## 7.- Sort Wallpapers }}}

## 8.- Change Wallpapers {{{

if $do_wallpaper; then
	set_wallpapers.sh
fi

## 8.- Change Wallpapers }}}

## 9.- Create Restore Point {{{

if $do_backup; then
	sudo timeshift --create --comment "$backup_message"
fi

## 9.- Create Restore Point }}}

## 10.- Delete Olds Restore Points {{{

# Get Snapshots
snapshots_lines=$(sudo timeshift --list | sed -n '/^-.*-$/, $ p' | sed -n '2,$ p')
snapshots=()

for line in "$snapshots_lines"; do
	snapshots+=($(echo "$line" | awk '{print $3}'))
done

snapshot_diff=$((${#snapshots[@]} - $max_backups - 1))

for i in seq 0 $snapshot_diff; do
	sudo timeshift --delete --snapshot "${snapshots[$i]}"
done

## 10.- Delete Olds Restore Points }}}

## 11.- Resume Output {{{

(( "${#git_untracked[@]}" > 0 )) && echo -e "There were $red${#git_untracked[@]}$reset files, please check it out."

## 11.- Resume Output }}}

