services:
  mariadb:
    image: mysql
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/Containers/mariadb/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: PHPMyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 12345678
      UPLOAD_LIMIT: 300M
    ports:
      - 7010:80
